name: Checkout
on: [push]

jobs:
    checkout-action:
      runs-on: ubuntu-latest
      steps:
        - name: List Files Before
          run: ls -a
        - name: Ckeckout
          uses: actions/checkout@v4.1.1
        - name: List Files After
          run: ls -a
    checkout-and-diplay-files:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -a
            - name: Checkout
              run: |
                git init
                git remote add origin "https://$GITUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: List Files After
              run: ls -a
