name: Repository Events
on: [push, pull_request, issues]

jobs:
    chekout-test:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v4.1.1
