# Before the start, install GitHub Actions VSCode extension
name: First Workflow
on: [push] # Whenever we push something to our repository, we need this workflow to run

# Jobs to run
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    # Create an array with objects
    steps:
      - name: Echo a string
        run: echo "Hello World"
      - name: Multiline command that checks Node and NPM versions
        run: | 
          node -v
          npm -v
  # Example of parallel job
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      # Key to view software version
      - name: View SW version
        run: sw_vers
  # Example of dependent job
  dependent-job:
    runs-on: windows-latest
    # Setting 'needs' key so this job depends on the firs job in this file (run-shell-commands)
    # This key can be a job ID or and array of job ID's []
    needs: run-shell-commands
    steps:
      - name: Echo a string
        run: Write-Output "Windows String"
      # 'doesnotexist' in this Error Step is a placeholder for a command that intentionally gives you an error (for demonstration purposes) 
      - name: Error Step
        run: doesnotexist
