name: Working Dir & Shells
on: [push]
jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display Working Directory & List Files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            # list current directory
            # list all files
            # echo the ID (SHA) of the commit
            # echo informations about the repository
            # echo default workspace for out machine (default directory used when we run any commands in our steps)
    display-wd-info-windows:
        runs-on: ubuntu-latest
        steps:
            - name: Display Working Directory & List Files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
                